"""
validators.py – Centralized input validation and sanitization for the OSG Portal.

Every user-supplied value MUST pass through one of these functions before it is
used in business logic, written to a data store, or echoed back to the client.

Rules:
  - Raise ValueError with a descriptive message on any violation.
  - Return the cleaned / normalized value on success.
  - Never swallow exceptions silently.
"""

import re
import os
import html
import datetime
from typing import List

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Maximum sizes
MAX_TEXT_DEFAULT   = 500    # characters
MAX_TEXT_SHORT     = 100    # username, staff name, sr_no …
MAX_TEXT_LONG      = 50000  # address, notes, remarks (notes grow over time as history is appended)
MAX_FILE_SIZE_MB   = 500    # 500 MB hard limit per uploaded file
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
MAX_CLAIMS_PER_SUBMIT = 10  # maximum claim items in one submission
MAX_EXPORT_IDS     = 2000   # max claim IDs in one export request

# Allowed file extensions and their corresponding magic-byte signatures
ALLOWED_EXTENSIONS = {'.xlsx', '.xls', '.pdf', '.jpg', '.jpeg', '.png'}

# First-byte magic signatures {extension: [list of accepted byte-prefixes]}
# Using bytes objects so we can do startswith() checks on raw file bytes.
MAGIC_BYTES = {
    '.xlsx': [b'PK\x03\x04'],                    # ZIP/OOXML
    '.xls':  [b'\xd0\xcf\x11\xe0'],              # OLE2 Compound Document
    '.pdf':  [b'%PDF'],
    '.jpg':  [b'\xff\xd8\xff'],
    '.jpeg': [b'\xff\xd8\xff'],
    '.png':  [b'\x89PNG'],
}

# Allowed claim statuses – the ONLY values the system accepts from external input.
ALLOWED_STATUSES = {
    "submitted",
    "registered",
    "follow up",
    "repair completed",
    "replacement approved",
    "rejected",
    "cancelled",
    "closed",
    "no issue/oncall resolution",
    "no issue",
    "oncall resolution",
}


# Allowed search types for claim-status-lookup
ALLOWED_SEARCH_TYPES = {"mobile", "claim_id"}

# Characters that trigger spreadsheet formula injection when leading a cell value.
# We strip these from the START of any text destined for Google Sheets.
FORMULA_INJECTION_CHARS = ('=', '+', '-', '@', '\t', '\r')

# Pattern for claim IDs generated by the app (e.g. CLM-1713800400)
CLAIM_ID_RE = re.compile(r'^CLM-\d{6,15}$')

# Safe token pattern: exactly 64 lowercase hex characters
RESET_TOKEN_RE = re.compile(r'^[0-9a-f]{64}$')

# Date patterns we accept from the UI
DATE_FORMATS = ['%Y-%m-%d', '%d-%m-%Y']


# ---------------------------------------------------------------------------
# Core text sanitizer
# ---------------------------------------------------------------------------

def sanitize_text(
    value,
    max_len: int = MAX_TEXT_DEFAULT,
    allow_newlines: bool = False,
    field_name: str = "field",
    sheet_destined: bool = False,
) -> str:
    """
    Clean and validate a free-text user input.

    Steps:
      1. Coerce to str, strip whitespace.
      2. Remove null bytes and ASCII control characters (optionally keep newlines).
      3. HTML-escape to neutralise any embedded HTML/script.
      4. Reject if result exceeds max_len.
      5. If sheet_destined=True, strip leading formula-injection characters.

    Returns the sanitized string.
    Raises ValueError if any constraint is violated.
    """
    if value is None:
        return ""

    text = str(value).strip()

    # Remove null bytes
    text = text.replace('\x00', '')

    # Strip ASCII control characters (except newline/tab if allowed)
    if allow_newlines:
        # Keep \n and \r\n, remove other control chars
        text = re.sub(r'[\x01-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)
    else:
        # Remove ALL control characters including newline/tab
        text = re.sub(r'[\x00-\x1f\x7f]', '', text)
        text = text.strip()

    # HTML-escape to neutralise <script>, onclick=, etc.
    text = html.escape(text, quote=True)

    if len(text) > max_len:
        raise ValueError(
            f"{field_name} is too long (max {max_len} characters, got {len(text)})."
        )

    # Spreadsheet formula injection prevention
    if sheet_destined and text and text[0] in FORMULA_INJECTION_CHARS:
        text = "'" + text   # prefix with single-quote to force text interpretation

    return text


# ---------------------------------------------------------------------------
# Specific field validators
# ---------------------------------------------------------------------------

def validate_mobile(value) -> str:
    """
    Validate and normalise a 10-digit Indian mobile number.

    Accepts strings or numbers. Strips .0 suffixes (from Excel float reads).
    Returns the normalised 10-digit string.
    Raises ValueError on any violation.
    """
    if value is None:
        raise ValueError("Mobile number is required.")

    mobile = str(value).strip()

    # Strip trailing .0 that pandas sometimes adds
    if mobile.endswith('.0'):
        mobile = mobile[:-2]

    # Remove spaces, dashes, parentheses commonly pasted by users
    mobile = re.sub(r'[\s\-\(\)]', '', mobile)

    # Strip country code prefix if present
    if mobile.startswith('+91'):
        mobile = mobile[3:]
    elif mobile.startswith('91') and len(mobile) == 12:
        mobile = mobile[2:]

    if not mobile.isdigit():
        raise ValueError("Mobile number must contain digits only.")

    if len(mobile) != 10:
        raise ValueError(
            f"Mobile number must be exactly 10 digits (got {len(mobile)})."
        )

    return mobile


def validate_date_str(value, field_name: str = "date") -> str:
    """
    Validate a date string, accepting YYYY-MM-DD or DD-MM-YYYY.

    Returns the value as-is (in the format provided) if valid.
    Raises ValueError if the string is not a recognisable date.
    """
    if not value or str(value).strip() in ('', 'nan', 'None', 'null'):
        return ""   # empty dates are allowed – caller decides if required

    s = str(value).strip()

    # Quick reject: must match one of our accepted patterns before parsing
    date_pattern = re.compile(
        r'^\d{4}-\d{2}-\d{2}$'          # YYYY-MM-DD
        r'|^\d{2}-\d{2}-\d{4}$'         # DD-MM-YYYY
    )
    if not date_pattern.match(s):
        raise ValueError(
            f"'{field_name}' has an invalid date format '{s}'. "
            "Expected YYYY-MM-DD or DD-MM-YYYY."
        )

    # Attempt actual parse to catch invalid calendar dates (e.g. 2025-02-30)
    parsed = None
    for fmt in DATE_FORMATS:
        try:
            parsed = datetime.datetime.strptime(s, fmt)
            break
        except ValueError:
            continue

    if parsed is None:
        raise ValueError(f"'{field_name}' value '{s}' is not a valid calendar date.")

    # Sanity-check: reject dates more than 5 years in the future
    max_future = datetime.datetime.now() + datetime.timedelta(days=5 * 365)
    if parsed > max_future:
        raise ValueError(
            f"'{field_name}' value '{s}' is implausibly far in the future."
        )

    return s


def validate_claim_id(value, field_name: str = "claim_id") -> str:
    """
    Validate a claim ID against the expected CLM-<digits> pattern.

    Returns the stripped claim ID string on success.
    Raises ValueError on mismatch.
    """
    if not value:
        raise ValueError(f"{field_name} is required.")

    cid = str(value).strip()

    if not CLAIM_ID_RE.match(cid):
        raise ValueError(
            f"'{field_name}' value '{cid}' is not a valid claim ID. "
            "Expected format: CLM-<digits>."
        )

    return cid


def validate_status(value) -> str:
    """
    Validate that a status value is in the allowed whitelist.

    Returns the title-cased normalised status string.
    Raises ValueError if not in whitelist.
    """
    if not value:
        raise ValueError("Status is required.")

    status_raw = str(value).strip()
    status_lower = status_raw.lower()

    if status_lower not in ALLOWED_STATUSES:
        allowed_display = ", ".join(sorted(ALLOWED_STATUSES))
        raise ValueError(
            f"Status '{status_raw}' is not permitted. "
            f"Allowed values: {allowed_display}."
        )

    # Return in the original casing from the whitelist (title-like)
    return status_raw


def validate_file_upload(file_obj, field_name: str = "file") -> None:
    """
    Validate an uploaded file object (werkzeug FileStorage).

    Checks:
      1. Filename is not empty.
      2. Extension is in the allowlist.
      3. File size does not exceed MAX_FILE_SIZE_BYTES (reads stream position).
      4. First bytes match expected magic signature for the extension.

    Does NOT save the file.  Resets the stream to position 0 before returning
    so the caller can read the file normally.

    Raises ValueError on any violation.
    """
    if file_obj is None or not file_obj.filename:
        raise ValueError(f"No file provided for '{field_name}'.")

    filename = file_obj.filename.strip()
    _, ext = os.path.splitext(filename.lower())

    # 1. Extension check
    if ext not in ALLOWED_EXTENSIONS:
        raise ValueError(
            f"File '{filename}' has a disallowed extension '{ext}'. "
            f"Allowed: {', '.join(sorted(ALLOWED_EXTENSIONS))}."
        )

    # 2. Size check – read stream to EOF and check length
    file_obj.stream.seek(0, 2)          # seek to end
    file_size = file_obj.stream.tell()
    file_obj.stream.seek(0)             # rewind

    if file_size > MAX_FILE_SIZE_BYTES:
        raise ValueError(
            f"File '{filename}' is too large "
            f"({file_size // (1024*1024)} MB). "
            f"Maximum allowed size is {MAX_FILE_SIZE_MB} MB."
        )

    if file_size == 0:
        raise ValueError(f"File '{filename}' is empty.")

    # 3. Magic-byte (MIME sniffing) check
    header = file_obj.stream.read(16)
    file_obj.stream.seek(0)             # rewind for caller

    expected_signatures = MAGIC_BYTES.get(ext, [])
    if expected_signatures:
        if not any(header.startswith(sig) for sig in expected_signatures):
            raise ValueError(
                f"File '{filename}' does not appear to be a valid "
                f"{ext.lstrip('.')} file (magic-byte mismatch). "
                "Do not rename files to bypass the upload filter."
            )


def validate_search_type(value) -> str:
    """
    Validate the search_type parameter for claim-status-lookup.

    Returns the normalised lowercase search type string.
    Raises ValueError if not in allowed set.
    """
    if not value:
        raise ValueError("search_type is required.")

    st = str(value).strip().lower()

    if st not in ALLOWED_SEARCH_TYPES:
        raise ValueError(
            f"search_type '{value}' is not valid. "
            f"Allowed values: {', '.join(sorted(ALLOWED_SEARCH_TYPES))}."
        )

    return st


def validate_claim_ids_list(value) -> List[str]:
    """
    Validate a list of claim IDs submitted for bulk export.

    Expects a Python list (already parsed from JSON).
    Validates each item against CLAIM_ID_RE.
    Enforces maximum of MAX_EXPORT_IDS items.

    Returns the cleaned list.
    Raises ValueError on any violation.
    """
    if value is None:
        return []

    if not isinstance(value, list):
        raise ValueError("claim_ids must be a JSON array.")

    if len(value) > MAX_EXPORT_IDS:
        raise ValueError(
            f"Too many claim IDs ({len(value)}). "
            f"Maximum is {MAX_EXPORT_IDS} per export."
        )

    cleaned = []
    for i, cid in enumerate(value):
        if not isinstance(cid, str):
            raise ValueError(
                f"claim_ids[{i}] must be a string, got {type(cid).__name__}."
            )
        cleaned.append(validate_claim_id(cid, field_name=f"claim_ids[{i}]"))

    return cleaned


def validate_reset_token(value) -> str:
    """
    Validate a password-reset token is exactly 64 lowercase hex characters.

    Raises ValueError on mismatch.
    """
    if not value:
        raise ValueError("Reset token is missing.")

    token = str(value).strip()

    if not RESET_TOKEN_RE.match(token):
        raise ValueError("Invalid or malformed reset token.")

    return token


def validate_password_strength(value, field_name: str = "password") -> str:
    """
    Enforce minimum password complexity:
      - At least 8 characters
      - At least 1 digit OR 1 special character

    Returns the password as-is (do not mutate passwords).
    Raises ValueError on any violation.
    """
    if not value:
        raise ValueError(f"{field_name} is required.")

    pwd = str(value)  # do NOT strip – whitespace in passwords is intentional

    if len(pwd) < 8:
        raise ValueError(
            f"{field_name} must be at least 8 characters long."
        )

    has_digit   = bool(re.search(r'\d', pwd))
    has_special = bool(re.search(r'[^A-Za-z0-9]', pwd))

    if not (has_digit or has_special):
        raise ValueError(
            f"{field_name} must contain at least one digit or special character."
        )

    return pwd


def validate_username(value) -> str:
    """
    Validate a username: alphanumeric + underscore/hyphen, 1–50 chars.

    Raises ValueError on violation.
    """
    if not value:
        raise ValueError("Username is required.")

    username = str(value).strip()

    if not re.match(r'^[A-Za-z0-9_\-]{1,50}$', username):
        raise ValueError(
            "Username must be 1–50 characters and contain only "
            "letters, digits, underscores, or hyphens."
        )

    return username


def validate_integer_range(value, min_val: int, max_val: int, field_name: str = "value") -> int:
    """
    Validate an integer is within [min_val, max_val].

    Accepts int, float, or numeric string.
    Returns the validated integer.
    Raises ValueError on violation.
    """
    try:
        num = int(float(str(value)))
    except (ValueError, TypeError):
        raise ValueError(f"'{field_name}' must be a number.")

    if not (min_val <= num <= max_val):
        raise ValueError(
            f"'{field_name}' must be between {min_val} and {max_val} (got {num})."
        )

    return num


def validate_boolean(value, field_name: str = "value") -> bool:
    """
    Coerce a JSON boolean/string/int to a strict Python bool.

    Accepts: True, False, 1, 0, "true", "false", "yes", "no".
    Raises ValueError on anything else.
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, int) and value in (0, 1):
        return bool(value)
    if isinstance(value, str):
        if value.lower() in ('true', '1', 'yes'):
            return True
        if value.lower() in ('false', '0', 'no'):
            return False

    raise ValueError(
        f"'{field_name}' must be a boolean (true/false), got '{value}'."
    )


def validate_time_slot(value) -> str:
    """
    Validate a time-slot string like '10:00 AM' or '14:30'.
    Only alphanumeric characters, spaces, colons, and AM/PM are allowed.
    Max 10 characters.
    """
    if not value:
        return ""

    ts = str(value).strip()

    if not re.match(r'^[A-Za-z0-9: ]{1,20}$', ts):
        raise ValueError(
            f"Invalid time slot format '{ts}'. "
            "Only letters, digits, spaces, and colons are allowed."
        )

    return ts
